server:
  port: 8081
  tomcat:
    threads:
      # 最少线程数
      min-spare: 10
      # 最多线程数
      max: 15
    # 最大连接数
    max-connections: 30
    # 最大等待数
    accept-count: 10


spring:
  application:
    name: bridge

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bridge?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: